#include <catch2/catch_test_macros.hpp>
#include <catch2/generators/catch_generators.hpp>
#include <catch2/matchers/catch_matchers_floating_point.hpp>

#include <algorithm>
#include <cmath>
#include <limits>
#include <vector>

#include "riskengine/concepts.hpp"
#include "riskengine/methods/analytic/black_scholes.hpp"

using namespace riskengine;
using Catch::Matchers::WithinRel;

static_assert(Pricer<BlackScholes>);

namespace {

struct Reference {
    const char* name;
    double s, k, r, q, sigma, t;
    OptionType type;
    double price, delta, gamma, vega, theta, rho;
};

// Generated by tools/bs_reference.py: mpmath at 50 digits, Greeks as numerical derivatives of
// the price (independent of the closed-form Greek formulas under test).
const std::vector<Reference> kReferences = {
    {"canonical call", 100, 100, 0.05, 0, 0.2, 1, OptionType::Call,
     10.450583572185567, 0.63683065117561907, 0.018762017345846894, 37.524034691693788, -6.4140275464381958, 53.23248154537634},
    {"canonical put", 100, 100, 0.05, 0, 0.2, 1, OptionType::Put,
     5.5735260222569677, -0.36316934882438093, 0.018762017345846894, 37.524034691693788, -1.6578804239346258, -41.890460904695061},
    {"dividend call", 100, 95, 0.03, 0.02, 0.25, 0.5, OptionType::Call,
     9.8319487257004147, 0.65138750198952649, 0.02056845628853121, 25.710570360664012, -6.7840716303845171, 27.653400736626117},
    {"dividend put", 100, 95, 0.03, 0.02, 0.25, 0.5, OptionType::Put,
     4.4125996130745622, -0.33866233175964157, 0.02056845628853121, 25.710570360664012, -5.9566022700141246, -19.139416394519359},
    {"Hull 15.6 call", 42, 40, 0.1, 0, 0.2, 0.5, OptionType::Call,
     4.7594223928715332, 0.77913129094266894, 0.049962670405911856, 8.8134150596028513, -4.5590921945926265, 13.982045913360281},
    {"Hull 15.6 put", 42, 40, 0.1, 0, 0.2, 0.5, OptionType::Put,
     0.80859937290009358, -0.22086870905733106, 0.049962670405911856, 8.8134150596028513, -0.75417449658977046, -5.042542576653999},
    {"wing K=200 call", 100, 200, 0.05, 0, 0.2, 0.25, OptionType::Call,
     9.910203707027289e-12, 7.0696239599892417e-12, 4.8770564909680804e-12, 2.4385282454840402e-9, -1.0102639078082109e-9, 1.7426304807297422e-10},
    {"wing K=200 put", 100, 200, 0.05, 0, 0.2, 0.25, OptionType::Put,
     97.515560098786196, -0.99999999999293038, 4.8770564909680804e-12, 2.4385282454840402e-9, 9.8757780039285504, -49.378890024519808},
    {"wing K=50 call", 100, 50, 0.05, 0, 0.2, 0.25, OptionType::Call,
     50.621109975306747, 0.99999999999940477, 4.3107496462417471e-13, 2.1553748231208736e-10, -2.4689445013179015, 12.344722506158432},
    {"wing K=50 put", 100, 50, 0.05, 0, 0.2, 0.25, OptionType::Put,
     8.1820893808163969e-13, -5.9523481887622984e-13, 4.3107496462417471e-13, 2.1553748231208736e-10, -8.3197908383549712e-11, -1.5085422706426156e-11},
};

MarketState market(double s, double r, double q, double sigma) {
    return MarketState{Spot{s}, Rate{r}, Rate{q}, Vol{sigma}};
}

VanillaOption option(double k, double t, OptionType type) {
    return VanillaOption{Strike{k}, Maturity{t}, type};
}

bool all_finite(const Greeks& g) {
    return std::isfinite(g.delta) && std::isfinite(g.gamma) && std::isfinite(g.vega) &&
           std::isfinite(g.theta) && std::isfinite(g.rho);
}

// Grid shared by the invariant tests: moneyness 0.5-2, 1 day to 5 years, low to high vol.
const std::vector<double> kStrikes = {50, 60, 75, 90, 100, 110, 125, 150, 200};
const std::vector<double> kMaturities = {1.0 / 365, 7.0 / 365, 30.0 / 365, 0.25, 1, 2, 5};
const std::vector<double> kVols = {0.05, 0.1, 0.2, 0.5, 1.0};

} // namespace

TEST_CASE("Black-Scholes matches high-precision reference values to 1e-9", "[bs][reference]") {
    // Validation gate of docs/model_risk_report.md 3.1. Relative tolerance, so the 1e-12 wing
    // prices are held to the same 9 significant digits as the at-the-money ones.
    constexpr double tol = 1e-9;
    for (const auto& ref : kReferences) {
        INFO(ref.name);
        const auto o = option(ref.k, ref.t, ref.type);
        const auto m = market(ref.s, ref.r, ref.q, ref.sigma);
        const Greeks g = black_scholes_greeks(o, m);
        CHECK_THAT(black_scholes_price(o, m), WithinRel(ref.price, tol));
        CHECK_THAT(g.delta, WithinRel(ref.delta, tol));
        CHECK_THAT(g.gamma, WithinRel(ref.gamma, tol));
        CHECK_THAT(g.vega, WithinRel(ref.vega, tol));
        CHECK_THAT(g.theta, WithinRel(ref.theta, tol));
        CHECK_THAT(g.rho, WithinRel(ref.rho, tol));
    }
}

TEST_CASE("Pricer returns a deterministic Estimate", "[bs]") {
    const BlackScholes pricer{option(100, 1, OptionType::Call)};
    const Estimate e = pricer.price(market(100, 0.05, 0, 0.2));
    CHECK_THAT(e.value, WithinRel(10.450583572185567, 1e-12));
    CHECK(e.std_error == 0.0);
    CHECK(e.discretization == 0.0);
}

TEST_CASE("Display conventions: vega per vol point, theta per calendar day", "[bs][conventions]") {
    const Greeks g = black_scholes_greeks(option(100, 1, OptionType::Call), market(100, 0.05, 0, 0.2));
    CHECK_THAT(vega_per_vol_point(g), WithinRel(0.37524034691693788, 1e-9));
    CHECK_THAT(theta_per_calendar_day(g), WithinRel(-6.4140275464381958 / 365.0, 1e-9));
}

TEST_CASE("Put-call parity holds to ~1e-14 across the grid", "[bs][invariant]") {
    const double r = 0.03, q = 0.01, s = 100;
    double worst = 0.0;
    for (double k : kStrikes)
        for (double t : kMaturities)
            for (double sigma : kVols) {
                const auto m = market(s, r, q, sigma);
                const double c = black_scholes_price(option(k, t, OptionType::Call), m);
                const double p = black_scholes_price(option(k, t, OptionType::Put), m);
                const double fwd = s * std::exp(-q * t) - k * std::exp(-r * t);
                // Relative to the size of the terms that are being differenced.
                worst = std::max(worst, std::abs(c - p - fwd) / (s + k));
            }
    INFO("worst relative parity error: " << worst);
    CHECK(worst <= 1e-14);
}

TEST_CASE("No-arbitrage bounds, monotonicity and strike convexity", "[bs][invariant]") {
    const double r = 0.03, q = 0.01, s = 100;
    for (double t : kMaturities)
        for (double sigma : kVols) {
            const auto m = market(s, r, q, sigma);
            const double df_r = std::exp(-r * t), df_q = std::exp(-q * t);
            std::vector<double> calls;
            for (double k : kStrikes) {
                INFO("K=" << k << " T=" << t << " sigma=" << sigma);
                const double c = black_scholes_price(option(k, t, OptionType::Call), m);
                const double p = black_scholes_price(option(k, t, OptionType::Put), m);
                const double slack = 1e-12 * (s + k);
                CHECK(c >= std::max(0.0, s * df_q - k * df_r) - slack);
                CHECK(c <= s * df_q + slack);
                CHECK(p >= std::max(0.0, k * df_r - s * df_q) - slack);
                CHECK(p <= k * df_r + slack);

                const Greeks g = black_scholes_greeks(option(k, t, OptionType::Call), m);
                CHECK(g.delta >= 0.0);
                CHECK(g.delta <= df_q);
                CHECK(g.gamma >= 0.0);
                CHECK(g.vega >= 0.0);
                calls.push_back(c);
            }
            // dC/dK < 0 and butterflies >= 0 (strike grid is not uniform: use divided differences).
            for (std::size_t i = 0; i + 1 < kStrikes.size(); ++i) CHECK(calls[i + 1] <= calls[i] + 1e-12);
            for (std::size_t i = 0; i + 2 < kStrikes.size(); ++i) {
                const double left = (calls[i + 1] - calls[i]) / (kStrikes[i + 1] - kStrikes[i]);
                const double right = (calls[i + 2] - calls[i + 1]) / (kStrikes[i + 2] - kStrikes[i + 1]);
                CHECK(right >= left - 1e-12);
            }
        }
}

TEST_CASE("Closed-form Greeks agree with finite differences of the price", "[bs][greeks]") {
    // Independent of the reference table: covers dividends, puts and the whole grid. Central
    // differences with relative bumps near the optimal h ~ eps^{1/3} (eps^{1/4} for gamma).
    const double r = 0.03, q = 0.01, s = 100;
    const auto type = GENERATE(OptionType::Call, OptionType::Put);
    for (double k : kStrikes)
        for (double t : {30.0 / 365, 0.25, 1.0, 5.0})
            for (double sigma : {0.1, 0.2, 0.5}) {
                INFO("K=" << k << " T=" << t << " sigma=" << sigma << " put=" << (type == OptionType::Put));
                const auto o = option(k, t, type);
                auto px = [&](double s_, double r_, double sigma_, double t_) {
                    return black_scholes_price(option(k, t_, type), market(s_, r_, q, sigma_));
                };
                const Greeks g = black_scholes_greeks(o, market(s, r, q, sigma));
                const double hs = 1e-4 * s, hs2 = 1e-3 * s, hv = 1e-5, hr = 1e-5, ht = 1e-5 * t;
                const double delta = (px(s + hs, r, sigma, t) - px(s - hs, r, sigma, t)) / (2 * hs);
                const double gamma = (px(s + hs2, r, sigma, t) - 2 * px(s, r, sigma, t) + px(s - hs2, r, sigma, t)) / (hs2 * hs2);
                const double vega = (px(s, r, sigma + hv, t) - px(s, r, sigma - hv, t)) / (2 * hv);
                const double rho = (px(s, r + hr, sigma, t) - px(s, r - hr, sigma, t)) / (2 * hr);
                const double theta = -(px(s, r, sigma, t + ht) - px(s, r, sigma, t - ht)) / (2 * ht);

                // Absolute floor on the scale of the price: FD cannot resolve Greeks whose
                // contribution is below the rounding of the price itself.
                const double abs_floor = 1e-6;
                CHECK(std::abs(g.delta - delta) <= 1e-6 * std::abs(delta) + abs_floor);
                CHECK(std::abs(g.gamma - gamma) <= 1e-4 * std::abs(gamma) + abs_floor);
                CHECK(std::abs(g.vega - vega) <= 1e-6 * std::abs(vega) + abs_floor);
                CHECK(std::abs(g.rho - rho) <= 1e-6 * std::abs(rho) + abs_floor);
                CHECK(std::abs(g.theta - theta) <= 1e-6 * std::abs(theta) + abs_floor);
            }
}

TEST_CASE("Edge cases: T -> 0 and sigma -> 0 give intrinsic values, never NaN", "[bs][edge]") {
    const double s = 100, r = 0.05, q = 0.02;
    const auto type = GENERATE(OptionType::Call, OptionType::Put);
    const double phi = type == OptionType::Call ? 1.0 : -1.0;

    SECTION("expired option (T = 0) is worth its intrinsic value") {
        for (double k : {80.0, 100.0, 120.0}) {
            const auto o = option(k, 0.0, type);
            const auto m = market(s, r, q, 0.2);
            CHECK(black_scholes_price(o, m) == std::max(0.0, phi * (s - k)));
            const Greeks g = black_scholes_greeks(o, m);
            CHECK(all_finite(g));
            CHECK(g.gamma == 0.0);
            CHECK(g.vega == 0.0);
        }
    }

    SECTION("zero vol is worth the discounted forward intrinsic value") {
        const double t = 1.0;
        for (double k : {80.0, 100.0, 120.0}) {
            const auto o = option(k, t, type);
            const double intrinsic = std::max(0.0, phi * (s * std::exp(-q * t) - k * std::exp(-r * t)));
            CHECK_THAT(black_scholes_price(o, market(s, r, q, 0.0)), WithinRel(intrinsic, 1e-15));
            const Greeks g = black_scholes_greeks(o, market(s, r, q, 0.0));
            CHECK(all_finite(g));
            CHECK(g.gamma == 0.0);
            CHECK(g.vega == 0.0);
        }
    }

    SECTION("the degenerate branch is the limit of the regular formulas") {
        for (double k : {80.0, 120.0}) {
            const auto o = option(k, 1.0, type);
            const double at_zero = black_scholes_price(o, market(s, r, q, 0.0));
            const double near_zero = black_scholes_price(o, market(s, r, q, 1e-8));
            CHECK(std::abs(at_zero - near_zero) <= 1e-12 * s);
            const Greeks g0 = black_scholes_greeks(o, market(s, r, q, 0.0));
            const Greeks g1 = black_scholes_greeks(o, market(s, r, q, 1e-8));
            CHECK(std::abs(g0.delta - g1.delta) <= 1e-12);
            CHECK(std::abs(g0.theta - g1.theta) <= 1e-9 * s);
            CHECK(std::abs(g0.rho - g1.rho) <= 1e-9 * s);
        }
    }

    SECTION("tiny but nonzero T and sigma, including exactly at the money forward") {
        for (double t : {1e-300, 1e-16, 1e-8})
            for (double sigma : {1e-300, 1e-16, 1e-8, 0.2, 5.0})
                for (double k : {s * std::exp((r - q) * t), 50.0, 100.0, 200.0}) {
                    INFO("T=" << t << " sigma=" << sigma << " K=" << k);
                    const auto o = option(k, t, type);
                    const auto m = market(s, r, q, sigma);
                    const double v = black_scholes_price(o, m);
                    CHECK(std::isfinite(v));
                    CHECK(v >= 0.0);
                    CHECK(all_finite(black_scholes_greeks(o, m)));
                }
    }

    SECTION("very long maturity and very high vol") {
        for (double k : {50.0, 100.0, 200.0}) {
            const auto o = option(k, 100.0, type);
            const auto m = market(s, r, q, 3.0);
            const double v = black_scholes_price(o, m);
            CHECK(std::isfinite(v));
            CHECK(v >= 0.0);
            CHECK(all_finite(black_scholes_greeks(o, m)));
        }
    }
}

TEST_CASE("Normal CDF keeps relative precision in the left tail", "[normal]") {
    // 1 - N(8) would round to 0; the erfc form must not.
    CHECK_THAT(norm_cdf(-8.0), WithinRel(6.2209605742717841e-16, 1e-13));
    CHECK_THAT(norm_cdf(-30.0), WithinRel(4.906713927148187e-198, 1e-12));
    CHECK(norm_cdf(0.0) == 0.5);
}
