#include <catch2/catch_test_macros.hpp>

#include <cmath>
#include <stdexcept>
#include <vector>

#include "riskengine/concepts.hpp"
#include "riskengine/core/rng/random_stream.hpp"
#include "riskengine/core/stats/welford.hpp"
#include "riskengine/methods/analytic/black_scholes.hpp"
#include "riskengine/methods/montecarlo/engine.hpp"
#include "riskengine/models/gbm.hpp"
#include "riskengine/models/heston.hpp"
#include "riskengine/models/merton.hpp"
#include "riskengine/payoffs/vanilla.hpp"

using namespace riskengine;

static_assert(PathModel<HestonQE> && ParametrizedModel<HestonQE>);
static_assert(PathModel<HestonEuler> && ParametrizedModel<HestonEuler>);
static_assert(PathModel<Merton> && ParametrizedModel<Merton>);
static_assert(PathModel<GBM> && !ParametrizedModel<GBM>);

namespace {

// Generated by tools/model_reference.py: mpmath at 30 digits, adaptive tanh-sinh quadrature
// (Heston) and exact-arithmetic Poisson series (Merton), independent of the code under test.
struct HestonCase {
    const char* name;
    double s, k, r, q, t, v0, kappa, theta, xi, rho, call, digital;
};
const HestonCase kHeston[] = {
    {"feller_atm", 100, 100, 0.05, 0.0, 1.0, 0.04, 2.0, 0.04, 0.3, -0.7, 10.394218565150162, 0.5879250336756843},
    {"feller_k80", 100, 80, 0.05, 0.0, 1.0, 0.04, 2.0, 0.04, 0.3, -0.7, 25.044557201355678, 0.84500205340803719},
    {"feller_k120", 100, 120, 0.05, 0.0, 1.0, 0.04, 2.0, 0.04, 0.3, -0.7, 2.3326334892154766, 0.22280548168248587},
    {"andersen_case1", 100, 100, 0.0, 0.0, 10.0, 0.04, 0.5, 0.04, 1.0, -0.9, 13.084670136992362, 0.65508929125307123},
    {"short_dividend", 100, 95, 0.03, 0.02, 0.1, 0.09, 1.0, 0.06, 0.8, -0.5, 6.8393758435533678, 0.72651443596830321},
};
struct MertonCase {
    const char* name;
    double s, k, r, q, sigma, t, lambda, mu, delta, call;
};
const MertonCase kMerton[] = {
    {"crash_atm", 100, 100, 0.05, 0.0, 0.2, 1.0, 0.5, -0.1, 0.15, 11.661674787503717},
    {"crash_k80", 100, 80, 0.05, 0.0, 0.2, 1.0, 0.5, -0.1, 0.15, 25.29939336795346},
    {"frequent_short", 100, 110, 0.03, 0.01, 0.15, 0.25, 2.0, 0.05, 0.05, 0.91521889660478681},
};

HestonParams params(const HestonCase& c) { return {c.v0, c.kappa, c.theta, c.xi, c.rho}; }

} // namespace

TEST_CASE("Heston characteristic-function prices match the 30-digit reference", "[heston]") {
    for (const HestonCase& c : kHeston) {
        INFO(c.name);
        const double call = heston_price(OptionType::Call, c.s, c.k, c.r, c.q, c.t, params(c));
        const double put = heston_price(OptionType::Put, c.s, c.k, c.r, c.q, c.t, params(c));
        CHECK(std::abs(call / c.call - 1.0) < 1e-10);
        CHECK(std::abs(call - put - (c.s * std::exp(-c.q * c.t) - c.k * std::exp(-c.r * c.t))) < 1e-12 * c.s);
        CHECK(std::abs(heston_digital_call(c.s, c.k, c.r, c.q, c.t, params(c)) / c.digital - 1.0) < 1e-10);
    }
    // Andersen (2008), case I, a long maturity where the original Heston formulation breaks: 13.0847.
    CHECK(std::abs(heston_price(OptionType::Call, 100, 100, 0, 0, 10, {0.04, 0.5, 0.04, 1.0, -0.9}) - 13.0847) < 5e-5);
}

TEST_CASE("Heston without vol of vol is Black-Scholes at the integrated variance", "[heston]") {
    // xi -> 0: v_t = theta + (v0 - theta) e^{-kappa t}, deterministic; its mean over [0, T] is the
    // Black-Scholes variance. The price is smooth in xi and the first correction is linear (through
    // rho xi), so gap / xi must converge to a constant as xi -> 0. (Below xi ~ 1e-5 double precision
    // gives out: the characteristic function's 1/xi^2 terms cancel catastrophically.)
    const double t = 2.0;
    auto gap = [&](double xi, double k) {
        const HestonParams p{0.09, 1.5, 0.04, xi, -0.5};
        const double var = p.theta + (p.v0 - p.theta) * (1.0 - std::exp(-p.kappa * t)) / (p.kappa * t);
        return heston_price(OptionType::Call, 100, k, 0.03, 0.01, t, p) -
               detail::bs_price(OptionType::Call, 100, k, 0.03, 0.01, std::sqrt(var), t);
    };
    for (double k : {80.0, 100.0, 125.0}) {
        INFO(k);
        const double slope_3 = gap(1e-3, k) / 1e-3, slope_4 = gap(1e-4, k) / 1e-4;
        CHECK(std::abs(slope_3 - slope_4) < 0.05 * std::abs(slope_4));
        CHECK(std::abs(gap(1e-4, k)) < 1e-3);
    }
}

TEST_CASE("Heston parameters are validated", "[heston]") {
    CHECK_THROWS_AS(heston_price(OptionType::Call, 100, 100, 0, 0, 1, {0.04, 1.0, 0.04, 0.0, -0.5}),
                    std::invalid_argument);
    CHECK_THROWS_AS(heston_price(OptionType::Call, 100, 100, 0, 0, 1, {0.04, 1.0, 0.04, 0.5, -1.5}),
                    std::invalid_argument);
    CHECK(HestonParams{0.04, 2.0, 0.04, 0.3, -0.7}.feller());
    CHECK_FALSE(HestonParams{0.04, 0.5, 0.04, 1.0, -0.9}.feller());
}

TEST_CASE("Heston Monte Carlo (QE) agrees with the characteristic function", "[heston][montecarlo]") {
    // The plan's Phase 7 gate: within 4 standard errors, at a step small enough for the QE bias to be
    // negligible against them (report 8.3 measures the bias itself).
    for (const HestonCase& c : {kHeston[0], kHeston[2], kHeston[4]}) {
        INFO(c.name);
        const MarketState m{Spot{c.s}, Rate{c.r}, Rate{c.q}, Vol{0.0}};
        const MonteCarlo<HestonQE, VanillaPayoff> mc(VanillaPayoff{c.k, OptionType::Call}, Maturity{c.t},
                                                     MonteCarloConfig{.paths = 1u << 18, .steps = 32, .threads = 4},
                                                     params(c));
        const Estimate e = mc.price(m, SeedKey{2026});
        CHECK(std::abs(e.value - c.call) < 4.0 * e.std_error);
        CHECK(e.std_error < 0.02 * c.call);
    }
}

TEST_CASE("Merton series prices match the 30-digit reference", "[merton]") {
    for (const MertonCase& c : kMerton) {
        INFO(c.name);
        const MertonParams p{c.lambda, c.mu, c.delta};
        const double call = merton_price(OptionType::Call, c.s, c.k, c.r, c.q, c.sigma, c.t, p);
        const double put = merton_price(OptionType::Put, c.s, c.k, c.r, c.q, c.sigma, c.t, p);
        CHECK(std::abs(call / c.call - 1.0) < 1e-12);
        CHECK(std::abs(call - put - (c.s * std::exp(-c.q * c.t) - c.k * std::exp(-c.r * c.t))) < 1e-11 * c.s);
    }
    // No jumps: Black-Scholes, exactly.
    const MarketState m{Spot{100}, Rate{0.05}, Rate{0.0}, Vol{0.2}};
    const VanillaOption call{Strike{110}, Maturity{1}, OptionType::Call};
    CHECK(merton_price(OptionType::Call, 100, 110, 0.05, 0.0, 0.2, 1.0, {0.0, -0.1, 0.15}) ==
          black_scholes_price(call, m));
}

TEST_CASE("Merton exact simulation agrees with the series, over one step or many", "[merton][montecarlo]") {
    const MertonCase& c = kMerton[0];
    const MarketState m{Spot{c.s}, Rate{c.r}, Rate{c.q}, Vol{c.sigma}};
    for (std::uint32_t steps : {1u, 12u}) {
        INFO(steps);
        const MonteCarlo<Merton, VanillaPayoff> mc(VanillaPayoff{c.k, OptionType::Call}, Maturity{c.t},
                                                   MonteCarloConfig{.paths = 1u << 18, .steps = steps, .threads = 4},
                                                   MertonParams{c.lambda, c.mu, c.delta});
        const Estimate e = mc.price(m, SeedKey{7});
        CHECK(std::abs(e.value - c.call) < 4.0 * e.std_error);
    }
}

TEST_CASE("Poisson inversion has the right mean and variance", "[merton]") {
    RandomStream rng(SeedKey{3}, 0);
    Welford w;
    constexpr int n = 200'000;
    for (int i = 0; i < n; ++i) w.add(Merton::poisson_inverse(rng.uniform(), 1.7));
    CHECK(std::abs(w.mean() - 1.7) < 4.0 * std::sqrt(1.7 / n));
    CHECK(std::abs(w.variance() / 1.7 - 1.0) < 0.02);
    CHECK(Merton::poisson_inverse(0.0, 1.0) == 0);
}
