"""Generate include/riskengine/core/rng/sobol_directions.hpp.

Source: the Joe & Kuo (2008) "new-joe-kuo-6.21201" direction numbers, as redistributed with SciPy
(scipy/stats/_sobol_direction_numbers.npz, arrays `poly` and `vinit`). SciPy stores the full
primitive polynomial (leading and trailing 1 included) and the initial values m_1..m_s. Emitted
here as (degree s, inner coefficients a, m_1..m_s), the Joe-Kuo file format.

Usage: python3 tools/gen_sobol_directions.py [max_dimension]   (requires scipy)
"""
import os
import sys

import numpy as np
import scipy.stats

MAX_DIMENSION = int(sys.argv[1]) if len(sys.argv) > 1 else 1024
OUT = os.path.join(os.path.dirname(__file__), "..", "include", "riskengine", "core", "rng", "sobol_directions.hpp")

data = np.load(os.path.join(os.path.dirname(scipy.stats.__file__), "_sobol_direction_numbers.npz"))
poly, vinit = data["poly"], data["vinit"]

lines = []
for d in range(1, MAX_DIMENSION):  # dimension 0 is the van der Corput sequence, handled in code
    p = int(poly[d])
    s = p.bit_length() - 1
    a = (p >> 1) & ((1 << (s - 1)) - 1)
    m = [int(v) for v in vinit[d][:s]]
    assert all(v % 2 == 1 and v < (1 << (k + 1)) for k, v in enumerate(m)), (d, m)
    lines.append(f"    {{{s}, {a}, {{{', '.join(map(str, m))}}}}},")

header = f"""#pragma once

// Generated by tools/gen_sobol_directions.py. Do not edit.
//
// Sobol direction numbers of Joe & Kuo (2008), "new-joe-kuo-6.21201", dimensions 2..{MAX_DIMENSION}
// (dimension 1 is the van der Corput sequence and needs none). Each entry is (degree s of the
// primitive polynomial, its inner coefficients a, initial direction numbers m_1..m_s).

#include <cstdint>

namespace riskengine::sobol_data {{

struct Direction {{
    std::uint32_t degree;
    std::uint32_t coefficients;
    std::uint32_t m[18];
}};

inline constexpr std::uint32_t kMaxDimension = {MAX_DIMENSION};

inline constexpr Direction kDirections[kMaxDimension - 1] = {{
{chr(10).join(lines)}
}};

}} // namespace riskengine::sobol_data
"""
with open(OUT, "w") as f:
    f.write(header)
print(f"wrote {os.path.normpath(OUT)} ({MAX_DIMENSION} dimensions)")
